<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ورود Excel | حسابداری صنعتی</title>
<style>
body{margin:0;background:#07111f;color:#e9f3fb;font-family:Tahoma,sans-serif}.wrap{max-width:1150px;margin:40px auto;padding:0 20px}.card{background:#0a1b2b;border:1px solid #1b354b;border-radius:16px;padding:22px;margin-bottom:18px}h1{margin:0 0 8px}.muted{color:#8ba1b5;font-size:13px}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}button,select,input{border-radius:10px;padding:10px 13px;border:1px solid #29445e;background:#081522;color:#e9f3fb}button{background:#6ee7d0;color:#04121a;border:0;font-weight:700;cursor:pointer}.hidden{display:none}.error{color:#ffb6b6;white-space:pre-wrap}.ok{color:#6ee7d0}.mapping{display:grid;grid-template-columns:1fr 1fr;gap:10px}.maprow{display:grid;grid-template-columns:1fr 1fr;gap:10px;align-items:center;padding:10px;border:1px solid #173047;border-radius:10px}.preview{overflow:auto}.preview table{border-collapse:collapse;width:100%}.preview th,.preview td{border:1px solid #29445e;padding:8px;text-align:right}.danger{background:#efb0b0}@media(max-width:700px){.mapping{grid-template-columns:1fr}.maprow{grid-template-columns:1fr}}
</style></head>
<body><div class="wrap">
<div class="card"><h1>ورود اطلاعات از Excel</h1><div class="muted">فایل ابتدا خوانده و ستون‌ها/نمونه داده نمایش داده می‌شود؛ تا زمان اعتبارسنجی کامل هیچ داده‌ای ذخیره نمی‌شود.</div></div>
<div class="card"><h2>۱. فایل</h2><form id="inspectForm" class="row"><input id="excelFile" type="file" accept=".xlsx,.xls,.ods,.csv" required><button>خواندن فایل</button></form><div id="inspectMsg"></div></div>
<div id="mappingCard" class="card hidden"><h2>۲. نگاشت ستون‌ها</h2><div class="row"><label>موجودیت <select id="target"></select></label></div><div id="columns" class="mapping" style="margin-top:15px"></div><div class="row" style="margin-top:15px"><button id="validateBtn">اعتبارسنجی قبل از ذخیره</button></div><div id="validationMsg"></div></div>
<div id="resultCard" class="card hidden"><h2>۳. نتیجه اعتبارسنجی</h2><div id="result"></div><div id="preview" class="preview"></div><button id="importBtn" class="hidden">ذخیره داده‌های معتبر</button></div>
<div class="card"><a href="{{ route('backups.page') }}" style="color:#6ee7d0">← بازگشت به Backup</a></div>
</div>
<script>
let inspection=null,validation=null;
const csrf='{{ csrf_token() }}';
async function json(url,options={}){options.headers={...(options.headers||{}),'X-CSRF-TOKEN':csrf,'Accept':'application/json'};const r=await fetch(url,options);const d=await r.json().catch(()=>({message:'پاسخ نامعتبر از سرور'}));if(!r.ok)throw new Error(d.message||'عملیات ناموفق بود');return d}
function msg(id,text,cls=''){const e=document.getElementById(id);e.className=cls;e.textContent=text}
document.getElementById('inspectForm').onsubmit=async e=>{e.preventDefault();msg('inspectMsg','در حال خواندن…');const fd=new FormData();fd.append('file',document.getElementById('excelFile').files[0]);try{inspection=await json('{{ route('imports.excel.inspect') }}',{method:'POST',body:fd});buildTarget();showMapping();msg('inspectMsg','فایل معتبر است و ستون‌ها تشخیص داده شدند.','ok')}catch(e){msg('inspectMsg',e.message,'error')}};
function buildTarget(){const t=document.getElementById('target');t.innerHTML=Object.keys(inspection.targets).map(k=>'<option value="'+esc(k)+'">'+esc(k)+'</option>').join('');t.onchange=renderMapping}
function showMapping(){document.getElementById('mappingCard').classList.remove('hidden');renderMapping()}
function renderMapping(){const cols=document.getElementById('columns'),target=document.getElementById('target').value,allowed=inspection.targets[target]||[];cols.innerHTML=inspection.columns.map(h=>'<div class="maprow"><b>'+esc(h)+'</b><select data-source="'+esc(h)+'"><option value="">نادیده گرفتن</option>'+allowed.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join('')+'</select></div>').join('');document.getElementById('resultCard').classList.add('hidden')}
document.getElementById('validateBtn').onclick=async()=>{const mapping={};document.querySelectorAll('[data-source]').forEach(s=>mapping[s.dataset.source]=s.value||null);try{validation=await json('{{ route('imports.excel.validate') }}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:inspection.token,target:document.getElementById('target').value,mapping})});document.getElementById('resultCard').classList.remove('hidden');msg('validationMsg',validation.valid?'همه ردیف‌ها معتبر هستند.':'برخی ردیف‌ها خطا دارند.',validation.valid?'ok':'error');document.getElementById('result').textContent='تعداد ردیف‌های معتبر: '+validation.rows;if(Object.keys(validation.errors).length)document.getElementById('result').textContent+='\nخطاها:\n'+Object.entries(validation.errors).map(([r,e])=>'ردیف '+r+': '+e.join('، ')).join('\n');renderPreview(validation.preview);document.getElementById('importBtn').classList.toggle('hidden',!validation.valid||validation.rows===0)}catch(e){msg('validationMsg',e.message,'error')}};
function renderPreview(rows){const p=document.getElementById('preview');if(!rows.length){p.innerHTML='';return}const keys=Object.keys(rows[0]);p.innerHTML='<table><thead><tr>'+keys.map(k=>'<th>'+esc(k)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(String(r[k]??''))+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
document.getElementById('importBtn').onclick=async()=>{if(!confirm('پس از ذخیره، بازگرداندن این Import فقط با ابزارهای مستقل داده‌ای ممکن است. ادامه می‌دهید؟'))return;const mapping={};document.querySelectorAll('[data-source]').forEach(s=>mapping[s.dataset.source]=s.value||null);try{const d=await json('{{ route('imports.excel.import') }}',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:inspection.token,target:document.getElementById('target').value,mapping})});msg('validationMsg','Import با موفقیت انجام شد: '+d.rows+' ردیف.','ok');document.getElementById('importBtn').classList.add('hidden')}catch(e){msg('validationMsg',e.message,'error')}};
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
</script></body></html>