<?php
namespace App\Http\Controllers;
use App\Support\CompanyAuthorization; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class MasterDataController extends Controller {
 private array $defs=[
  'goods-categories'=>['table'=>'goods_categories','permission'=>'goods_category','title'=>'دسته‌بندی کالاها','fields'=>['code','name','parent_id'],'search'=>['code','name']],
  'units'=>['table'=>'units','permission'=>'unit','title'=>'واحدها','fields'=>['code','name','symbol','unit_type'],'search'=>['code','name']],
  'suppliers'=>['table'=>'suppliers','permission'=>'supplier','title'=>'تأمین‌کنندگان','fields'=>['code','name','national_id','phone','email','address'],'search'=>['code','name','phone']],
  'goods'=>['table'=>'goods','permission'=>'goods','title'=>'کالاها','fields'=>['code','name','category_id','purchasable','producible','sellable','description'],'search'=>['code','name']],
  'production-sections'=>['table'=>'production_sections','permission'=>'production_section','title'=>'قسمت‌های تولید','fields'=>['location_id','supervisor_personnel_id'],'search'=>[]],
  'locations'=>['table'=>'locations','permission'=>'location','title'=>'انبارها و محل‌ها','fields'=>['code','name','type'],'search'=>['code','name']],
  'production-routes'=>['table'=>'production_routes','permission'=>'production_route','title'=>'مسیرهای تولید','fields'=>['code','name','goods_id','description','status'],'search'=>['code','name']],
  'production-stages'=>['table'=>'production_stages','permission'=>'production_stage','title'=>'مراحل تولید','fields'=>['code','name','production_route_id','production_section_id','sequence','status'],'search'=>['code','name']],
  'production-operations'=>['table'=>'production_operations','permission'=>'production_operation','title'=>'عملیات تولید','fields'=>['code','name','production_stage_id','sequence','standard_duration_minutes','setup_duration_minutes','status'],'search'=>['code','name']],
  'productions'=>['table'=>'productions','permission'=>'production','title'=>'دستورهای تولید','fields'=>['number','goods_id','production_route_id','fiscal_year_id','planned_quantity','planned_start_at','planned_end_at','notes'],'search'=>['number']],
 ];
 public function index(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.view');$q=$module==='production-sections'?DB::table('production_sections as ps')->join('locations as l','l.id','=','ps.location_id')->where('l.company_id',$cid)->select('ps.*'):DB::table($d['table'])->where('company_id',$cid);if($term=trim((string)$request->query('q'))){$q->where(function($w)use($d,$term){foreach($d['search'] as $i=>$f){$i?$w->orWhere($f,'like','%'.$term.'%'):$w->where($f,'like','%'.$term.'%');}});} $rows=$q->latest('id')->paginate(20)->withQueryString();return view('master-data.index',['definition'=>$d,'module'=>$module,'rows'=>$rows]);}
 public function edit(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.update');$row=$module==='production-sections'?DB::table('production_sections as ps')->join('locations as l','l.id','=','ps.location_id')->where('ps.id',$id)->where('l.company_id',$cid)->select('ps.*')->first():DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->first();abort_unless($row,404);return view('master-data.form',['definition'=>$d,'module'=>$module,'options'=>$this->options($module,$cid),'row'=>$row,'editing'=>true]);}
 public function update(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.update');$row=$module==='production-sections'?DB::table('production_sections as ps')->join('locations as l','l.id','=','ps.location_id')->where('ps.id',$id)->where('l.company_id',$cid)->select('ps.*')->first():DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->first();abort_unless($row,404);$rules=[];foreach($d['fields'] as $f){$rules[$f]=match($f){'code','number'=>'required|string|max:100','name'=>'required|string|max:255','category_id','goods_id','production_route_id','production_stage_id','production_section_id','fiscal_year_id'=>'required|integer','sequence','standard_duration_minutes','setup_duration_minutes'=>'nullable|integer|min:0','planned_quantity'=>'required|numeric|gt:0','purchasable','producible','sellable'=>'nullable|boolean','status','type'=>'required|string|max:40','planned_start_at','planned_end_at'=>'nullable|date',default=>'nullable|string'};} $data=$request->validate($rules);
 foreach(['category_id'=>'goods_categories','goods_id'=>'goods','production_route_id'=>'production_routes','production_stage_id'=>'production_stages','production_section_id'=>'production_sections','fiscal_year_id'=>'fiscal_years'] as $field=>$table){if(isset($data[$field])){abort_unless(DB::table($table)->where('id',$data[$field])->when($table==='production_stages',fn($q)=>$q->whereIn('production_route_id',DB::table('production_routes')->where('company_id',$cid)->pluck('id')))->where(function($q)use($table,$cid){if(in_array($table,['production_stages']))return $q;return $q->where('company_id',$cid); })->exists(),422,'مرجع انتخاب‌شده متعلق به شرکت نیست.');}}foreach(['purchasable','producible','sellable'] as $f)if(array_key_exists($f,$d['fields']))$data[$f]=(bool)($data[$f]??false);$data['updated_at']=now();if($module==='production-sections'){abort_unless(DB::table('locations')->where('id',$data['location_id'])->where('company_id',$cid)->exists(),422,'محل تولید متعلق به شرکت نیست.');DB::table('production_sections')->where('id',$id)->update($data);}else{DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->update($data);}return redirect()->route('master.index',$module)->with('success','رکورد ویرایش شد.');}
 public function startProduction(Request $request,int $id){$cid=CompanyAuthorization::authorize($request,'production.supervise');DB::transaction(function()use($cid,$id){$p=DB::table('productions')->where('id',$id)->where('company_id',$cid)->lockForUpdate()->first();abort_unless($p,404);abort_unless($p->status==='draft',422,'تولید فقط از وضعیت پیش‌نویس قابل شروع است.');$stages=DB::table('production_stages')->where('production_route_id',$p->production_route_id)->where('status','active')->orderBy('sequence')->get();abort_unless($stages->isNotEmpty(),422,'مسیر تولید مرحله فعالی ندارد.');$snap=['production_id'=>$p->id,'route_id'=>$p->production_route_id,'stages'=>$stages->toArray()];DB::table('production_route_instances')->updateOrInsert(['production_id'=>$p->id],['production_route_id'=>$p->production_route_id,'snapshot'=>json_encode($snap),'updated_at'=>now(),'created_at'=>now()]);foreach($stages as $stage){$sr=DB::table('production_stage_runs')->insertGetId(['production_id'=>$p->id,'production_stage_id'=>$stage->id,'sequence'=>$stage->sequence,'status'=>'pending','planned_quantity'=>$p->planned_quantity,'created_at'=>now(),'updated_at'=>now()]);$ops=DB::table('production_operations')->where('production_stage_id',$stage->id)->where('status','active')->orderBy('sequence')->get();foreach($ops as $op)DB::table('production_operation_runs')->insert(['production_stage_run_id'=>$sr,'production_operation_id'=>$op->id,'sequence'=>$op->sequence,'status'=>'pending','planned_quantity'=>$p->planned_quantity,'created_at'=>now(),'updated_at'=>now()]);}DB::table('productions')->where('id',$p->id)->update(['status'=>'in_progress','started_at'=>now(),'updated_at'=>now()]);});return back()->with('success','تولید شروع شد و اجرای مراحل/عملیات ایجاد شد.');}
 public function deactivate(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.deactivate');$ok=$module==='production-sections'?DB::table('production_sections as ps')->join('locations as l','l.id','=','ps.location_id')->where('ps.id',$id)->where('l.company_id',$cid)->exists():DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->exists();abort_unless($ok,404);if($module==='production-sections')DB::table('production_sections')->where('id',$id)->update(['is_active'=>false,'updated_at'=>now()]); else DB::table($d['table'])->where('id',$id)->update(['is_active'=>false,'updated_at'=>now()]);return back()->with('success','رکورد غیرفعال شد.');}
 public function create(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.create');$options=$this->options($module,$cid);return view('master-data.form',['definition'=>$d,'module'=>$module,'options'=>$options]);}
 public function store(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.create');$rules=[];foreach($d['fields'] as $f){$rules[$f]=match($f){'code','number'=>'required|string|max:100','name'=>'required|string|max:255','category_id','goods_id','production_route_id','production_stage_id','fiscal_year_id'=>'required|integer','sequence','standard_duration_minutes','setup_duration_minutes'=>'nullable|integer|min:0','planned_quantity'=>'required|numeric|gt:0','purchasable','producible','sellable'=>'nullable|boolean','status','type'=>'required|string|max:40','planned_start_at','planned_end_at'=>'nullable|date',default=>'nullable|string'};} $data=$request->validate($rules);foreach(['category_id'=>'goods_categories','goods_id'=>'goods','production_route_id'=>'production_routes','production_stage_id'=>'production_stages','fiscal_year_id'=>'fiscal_years'] as $field=>$table){if(isset($data[$field])){abort_unless(DB::table($table)->where('id',$data[$field])->when($table==='production_stages',fn($q)=>$q->whereIn('production_route_id',DB::table('production_routes')->where('company_id',$cid)->pluck('id')))->when($table!=='production_stages',fn($q)=>$q->where('company_id',$cid))->exists(),422,'مرجع انتخاب‌شده متعلق به شرکت نیست.');}}if($module==='production-sections'){abort_unless(DB::table('locations')->where('id',$data['location_id'])->where('company_id',$cid)->exists(),422,'محل تولید متعلق به شرکت نیست.');}else{$data['company_id']=$cid;}$data['created_at']=now();$data['updated_at']=now();if(isset($data['purchasable']))foreach(['purchasable','producible','sellable'] as $f)$data[$f]=(bool)($data[$f]??false);DB::table($d['table'])->insert($data);return redirect()->route('master.index',$module)->with('success','رکورد با موفقیت ثبت شد.');}
 private function definition(string $m):array{abort_unless(isset($this->defs[$m]),404);return $this->defs[$m];}
 private function options(string $m,int $cid):array{return match($m){ 'goods-categories'=>['parents'=>DB::table('goods_categories')->where('company_id',$cid)->orderBy('name')->get()], 'production-sections'=>['locations'=>DB::table('locations')->where('company_id',$cid)->where('type','production')->where('is_active',true)->get(),'personnel'=>DB::table('personnel')->where('account_id',DB::table('companies')->where('id',$cid)->value('account_id'))->where('is_active',true)->get()], 'goods'=>['categories'=>DB::table('goods_categories')->where('company_id',$cid)->where('is_active',true)->orderBy('name')->get()], 'production-routes'=>['goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->where('producible',true)->orderBy('name')->get()], 'production-stages'=>['routes'=>DB::table('production_routes')->where('company_id',$cid)->orderBy('name')->get(),'sections'=>DB::table('production_sections as ps')->join('locations as l','l.id','=','ps.location_id')->where('l.company_id',$cid)->where('ps.is_active',true)->select('ps.id','l.name')->orderBy('l.name')->get()], 'production-operations'=>['stages'=>DB::table('production_stages as s')->join('production_routes as r','r.id','=','s.production_route_id')->where('r.company_id',$cid)->select('s.id','s.name')->orderBy('s.name')->get()], 'productions'=>['goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->where('producible',true)->orderBy('name')->get(),'routes'=>DB::table('production_routes')->where('company_id',$cid)->where('status','active')->orderBy('name')->get(),'fiscalYears'=>DB::table('fiscal_years')->where('company_id',$cid)->where('is_closed',false)->orderByDesc('id')->get()],default=>[]};}
}