<?php
namespace App\Http\Controllers;
use App\Support\CompanyAuthorization; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class MasterDataController extends Controller {
 private array $defs=[
  'suppliers'=>['table'=>'suppliers','permission'=>'supplier','title'=>'تأمین‌کنندگان','fields'=>['code','name','national_id','phone','email','address'],'search'=>['code','name','phone']],
  'goods'=>['table'=>'goods','permission'=>'goods','title'=>'کالاها','fields'=>['code','name','category_id','purchasable','producible','sellable','description'],'search'=>['code','name']],
  'locations'=>['table'=>'locations','permission'=>'location','title'=>'انبارها و محل‌ها','fields'=>['code','name','type'],'search'=>['code','name']],
  'production-routes'=>['table'=>'production_routes','permission'=>'production_route','title'=>'مسیرهای تولید','fields'=>['code','name','goods_id','description','status'],'search'=>['code','name']],
  'production-stages'=>['table'=>'production_stages','permission'=>'production_stage','title'=>'مراحل تولید','fields'=>['code','name','production_route_id','sequence','status'],'search'=>['code','name']],
  'production-operations'=>['table'=>'production_operations','permission'=>'production_operation','title'=>'عملیات تولید','fields'=>['code','name','production_stage_id','sequence','standard_duration_minutes','setup_duration_minutes','status'],'search'=>['code','name']],
  'productions'=>['table'=>'productions','permission'=>'production','title'=>'دستورهای تولید','fields'=>['number','goods_id','production_route_id','fiscal_year_id','planned_quantity','planned_start_at','planned_end_at','notes'],'search'=>['number']],
 ];
 public function index(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.view');$q=DB::table($d['table'])->where('company_id',$cid);if($term=trim((string)$request->query('q'))){$q->where(function($w)use($d,$term){foreach($d['search'] as $i=>$f){$i?$w->orWhere($f,'like','%'.$term.'%'):$w->where($f,'like','%'.$term.'%');}});} $rows=$q->latest('id')->paginate(20)->withQueryString();return view('master-data.index',['definition'=>$d,'module'=>$module,'rows'=>$rows]);}
 public function edit(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.update');$row=DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->first();abort_unless($row,404);return view('master-data.form',['definition'=>$d,'module'=>$module,'options'=>$this->options($module,$cid),'row'=>$row,'editing'=>true]);}
 public function update(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.update');$row=DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->first();abort_unless($row,404);$rules=[];foreach($d['fields'] as $f){$rules[$f]=match($f){'code','number'=>'required|string|max:100','name'=>'required|string|max:255','category_id','goods_id','production_route_id','production_stage_id','fiscal_year_id'=>'required|integer','sequence','standard_duration_minutes','setup_duration_minutes'=>'nullable|integer|min:0','planned_quantity'=>'required|numeric|gt:0','purchasable','producible','sellable'=>'nullable|boolean','status','type'=>'required|string|max:40','planned_start_at','planned_end_at'=>'nullable|date',default=>'nullable|string'};} $data=$request->validate($rules);foreach(['purchasable','producible','sellable'] as $f)if(array_key_exists($f,$d['fields']))$data[$f]=(bool)($data[$f]??false);$data['updated_at']=now();DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->update($data);return redirect()->route('master.index',$module)->with('success','رکورد ویرایش شد.');}
 public function deactivate(Request $request,string $module,int $id){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.deactivate');$ok=DB::table($d['table'])->where('id',$id)->where('company_id',$cid)->update(['is_active'=>false,'updated_at'=>now()]);abort_unless($ok,404);return back()->with('success','رکورد غیرفعال شد.');}
 public function create(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.create');$options=$this->options($module,$cid);return view('master-data.form',['definition'=>$d,'module'=>$module,'options'=>$options]);}
 public function store(Request $request,string $module){$d=$this->definition($module);$cid=CompanyAuthorization::authorize($request,$d['permission'].'.create');$rules=[];foreach($d['fields'] as $f){$rules[$f]=match($f){'code','number'=>'required|string|max:100','name'=>'required|string|max:255','category_id','goods_id','production_route_id','production_stage_id','fiscal_year_id'=>'required|integer','sequence','standard_duration_minutes','setup_duration_minutes'=>'nullable|integer|min:0','planned_quantity'=>'required|numeric|gt:0','purchasable','producible','sellable'=>'nullable|boolean','status','type'=>'required|string|max:40','planned_start_at','planned_end_at'=>'nullable|date',default=>'nullable|string'};} $data=$request->validate($rules);$data['company_id']=$cid;$data['created_at']=now();$data['updated_at']=now();if(isset($data['purchasable']))foreach(['purchasable','producible','sellable'] as $f)$data[$f]=(bool)($data[$f]??false);DB::table($d['table'])->insert($data);return redirect()->route('master.index',$module)->with('success','رکورد با موفقیت ثبت شد.');}
 private function definition(string $m):array{abort_unless(isset($this->defs[$m]),404);return $this->defs[$m];}
 private function options(string $m,int $cid):array{return match($m){ 'goods'=>['categories'=>DB::table('goods_categories')->where('company_id',$cid)->where('is_active',true)->orderBy('name')->get()], 'production-routes'=>['goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->where('producible',true)->orderBy('name')->get()], 'production-stages'=>['routes'=>DB::table('production_routes')->where('company_id',$cid)->orderBy('name')->get()], 'production-operations'=>['stages'=>DB::table('production_stages as s')->join('production_routes as r','r.id','=','s.production_route_id')->where('r.company_id',$cid)->select('s.id','s.name')->orderBy('s.name')->get()], 'productions'=>['goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->where('producible',true)->orderBy('name')->get(),'routes'=>DB::table('production_routes')->where('company_id',$cid)->where('status','active')->orderBy('name')->get(),'fiscalYears'=>DB::table('fiscal_years')->where('company_id',$cid)->where('is_closed',false)->orderByDesc('id')->get()],default=>[]};}
}