<?php
namespace App\Http\Controllers;
use App\Support\CompanyAuthorization; use App\Http\Controllers\SupplyRequestController; use App\Http\Controllers\PurchaseController; use App\Http\Controllers\PurchaseReceiptController; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class WorkflowPagesController extends Controller {
 public function supply(Request $r){$cid=CompanyAuthorization::authorize($r,'supply_request.view');return view('workflows.supply',['rows'=>DB::table('supply_requests')->where('company_id',$cid)->latest('id')->paginate(20),'goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->get(),'years'=>DB::table('fiscal_years')->where('company_id',$cid)->where('is_closed',false)->get(),'productions'=>DB::table('productions')->where('company_id',$cid)->latest('id')->get(),'orders'=>DB::table('orders')->where('company_id',$cid)->latest('id')->get()]);}
 public function purchasing(Request $r){$cid=CompanyAuthorization::authorize($r,'purchase.view');return view('workflows.purchasing',['rows'=>DB::table('purchases')->where('company_id',$cid)->latest('id')->paginate(20),'goods'=>DB::table('goods')->where('company_id',$cid)->where('purchasable',true)->get(),'suppliers'=>DB::table('suppliers')->where('company_id',$cid)->where('is_active',true)->get(),'requests'=>DB::table('supply_requests')->where('company_id',$cid)->whereIn('status',['shortage_pending','partially_supplied'])->get(),'years'=>DB::table('fiscal_years')->where('company_id',$cid)->where('is_closed',false)->get()]);}
 public function receipts(Request $r){$cid=CompanyAuthorization::authorize($r,'purchase.receipt.create');return view('workflows.receipts',['rows'=>DB::table('purchase_receipts')->where('company_id',$cid)->latest('id')->paginate(20),'purchases'=>DB::table('purchases')->where('company_id',$cid)->whereIn('status',['draft','partially_received'])->get(),'locations'=>DB::table('locations')->where('company_id',$cid)->where('type','warehouse')->where('is_active',true)->get(),'goods'=>DB::table('goods')->where('company_id',$cid)->where('is_active',true)->get()]);}
 public function storeReceipt(Request $r){$cid=CompanyAuthorization::authorize($r,'purchase.receipt.create');$d=$r->validate(['purchase_id'=>'required|integer','warehouse_location_id'=>'required|integer','received_at'=>'required|date','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.goods_id'=>'required|integer','items.*.quantity'=>'required|numeric|gt:0']);app(PurchaseReceiptController::class)->store($r);return back()->with('success','رسید خرید ثبت شد.');}
 public function labor(Request $r){$cid=CompanyAuthorization::authorize($r,'production.labor.create');return view('workflows.labor',['rows'=>DB::table('production_labor_entries')->where('company_id',$cid)->latest('id')->paginate(20),'personnel'=>DB::table('personnel')->where('account_id',$r->user()->account_id)->where('is_active',true)->get(),'runs'=>DB::table('production_operation_runs as r')->join('production_stage_runs as sr','sr.id','=','r.production_stage_run_id')->join('productions as p','p.id','=','sr.production_id')->where('p.company_id',$cid)->select('r.id','p.number')->latest('r.id')->get()]);}
 public function storeSupply(Request $r){app(SupplyRequestController::class)->store($r);return back()->with('success','درخواست تأمین ثبت شد.');}
 public function storePurchase(Request $r){app(PurchaseController::class)->store($r);return back()->with('success','خرید ثبت شد.');}
 public function storeLabor(Request $r){$cid=CompanyAuthorization::authorize($r,'production.labor.create');$d=$r->validate(['production_operation_run_id'=>'required|integer','personnel_id'=>'required|integer','measure_type'=>'required|in:hour,unit','measure_quantity'=>'required|numeric|gt:0','worked_at'=>'required|date','notes'=>'nullable|string']);$run=DB::table('production_operation_runs as r')->join('production_stage_runs as sr','sr.id','=','r.production_stage_run_id')->join('productions as p','p.id','=','sr.production_id')->where('r.id',$d['production_operation_run_id'])->where('p.company_id',$cid)->exists();abort_unless($run,422,'عملیات تولید نامعتبر است.');app(\App\Services\LaborCostService::class)->record($cid,(int)$d['production_operation_run_id'],(int)$d['personnel_id'],$d['measure_type'],(float)$d['measure_quantity'],$d['worked_at'],(int)$r->user()->id,$d['notes']??null);return back()->with('success','کارکرد ثبت شد.');}
 public function inventory(Request $r){$cid=CompanyAuthorization::authorize($r,'inventory.view');$rows=DB::table('inventory as i')->join('goods as g','g.id','=','i.goods_id')->join('locations as l','l.id','=','i.location_id')->where('i.company_id',$cid)->select('i.*','g.name as goods_name','g.code as goods_code','l.name as location_name')->orderBy('g.name')->paginate(30);return view('workflows.inventory',compact('rows'));}
}